import Head from 'next/head'
import { CSVLink } from "react-csv";

interface Data {
  id: number;
  center?: number[];
  diameter?: number;
  'cell count'?: number;
  'cell area'?: number;
  volume?: number;
}

export default function Home() {

  const data = '[{"id": 0, "center": [2369, 1858], "diameter": 98.488, "cell count": 0, "cell area": 0.0, "volume": 500.206}, {"id": 1, "center": [2125, 1837], "diameter": 101.1, "cell count": 1, "cell area": 143.0, "volume": 541.068}]'
  let correctedData: string = data.replace(/\'/g, '"');
  const jsonData: Data[] = JSON.parse(correctedData);

  const newData: { [key: string]: number | string }[] = [];

  jsonData.forEach((item) => {
    const newItem: { [key: string]: number | string } = {};
    Object.entries(item).forEach(([key, value]) => {
      if (Array.isArray(value)) {
        newItem[`${key}_x`] = value[0];
        newItem[`${key}_y`] = value[1];
      } else {
        newItem[key] = value;
      }
    });
    newData.push(newItem);
  });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button>
          <CSVLink 
            data={newData} 
            filename={"sumaryResult.csv"}
          >
            Download CSV
          </CSVLink>
        </button>
      </main>
    </>
  )
}
